expected_hash = "0x20a3af0435914ccd84b806164531b0cd36e37d4efb93efab76913a93e1f30996"
message = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
pk_x = "0x04b260954662e97f00cab9adb773a259097f7a274b83b113532bce27fa3fb96a"
pk_y = "0x2fd51571db6c08666b0edfbfbc57d432068bccd0110a39b166ab243da0037197"
sig = [
    1, 13, 119, 112, 212, 39, 233, 41, 84, 235, 255, 93, 245, 172, 186, 83, 157, 253, 76,
    77, 33, 128, 178, 15, 214, 67, 105, 107, 177, 234, 77, 48, 27, 237, 155, 84, 39, 84,
    247, 27, 22, 8, 176, 230, 24, 115, 145, 220, 254, 122, 135, 179, 171, 4, 214, 202, 64,
    199, 19, 84, 239, 138, 124, 12
    ]
v="0x2f98e416d2695c36272eb38d1a9a1eefb33dbfbd9a1ca0a6cd3d664e06d025be" 
w_path_elements = ["0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544","0x233344555544"]
w_path_indices = [0,1,0,1,0,1,0,1,0,1]
k = "0x3333333333888888888849494949"
rsp = "0x3333333333888888888849494949"
chall = "0x3333333333888888888849494949"
t = "0x02f59d4427fb29daf9b5aa6a3f7de300da50498412d75d4bc65c86f72d86f488"